# Site settings
title: Mario Turco
description: I'm a Computer Science studente at University Federico II of Naples (Unina).
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://marioturco.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mario Turco
user_description: Prova Prova Test Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Computer Scientist
email: turcomario.na@gmail.com
#twitter_username: lorem_ipsum
github_username:  MarioTurco
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
