# Site settings
title: Mario Turco
description: Born in Torre del Greco(Naples) in 1998 and passionate about technology since I was a kid.I'm currently attending a Computer Sciences degree at the University of Naples Federico II and currently working on my Bachelor's degree dissertation. Looking forward to further explore Artificial Intelligence as well as Data Science.
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://marioturco.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mario Turco
#user_description: 
user_title: Computer Scientist
email: turcomario.na@gmail.com
linkedin_username: turcomario
github_username:  MarioTurco
#twitter_username: lorem_ipsum
#gplus_username:  lorem_ipsum
#show_projects: yes #comment this line to hide projects
# Google-analytics

google-analytics:
  id: "UA-167451604-1"

exclude: ['package.json', 'src' , 'node_modules']
